name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "
    CrateDB: ${{ matrix.cratedb-version }}
    SDK: ${{ matrix.sdk-tester-version }}
    "
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [
          '3.14',
        ]
        cratedb-version:
          - '6.3.1'
          #- 'nightly'  # Currently defunct. https://github.com/crate/crate/issues/19291
        sdk-tester-version:
          - '2.26.0113.001'  # (Jan 16, 2026) LIVE mode active
          - '2.26.0127.001'  # (Jan 28, 2026) LIVE mode paused
          - '2.26.0420.001'  # (Apr 21, 2026)

    env:
      CRATEDB_VERSION: '${{ matrix.cratedb-version }}'
      SDK_TESTER_VERSION: '${{ matrix.sdk-tester-version }}'
      UV_PYTHON_DOWNLOADS: never
      UV_SYSTEM_PYTHON: true

    services:
      cratedb:
        image: docker.io/crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432

    steps:

      - name: Acquire sources
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          cache-dependency-glob: |
            pyproject.toml
          cache-suffix: ${{ matrix.python-version }}
          enable-cache: true
          version: "latest"

      - name: Set up project
        run: |
          uv pip install --editable='.[develop,test]'

      - name: Run linters and software tests
        run: |
          poe check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
